/**
 * Phase 8: Offender Profiling & Case Management - Type Definitions
 */

/**
 * Offender profile
 */
export interface OffenderProfile {
  personId: string;
  name: string;
  photoUrl?: string;
  age: number;
  gender: 'Male' | 'Female' | 'Other';
  role: 'Accused' | 'Victim' | 'Witness';
  riskScore: number; // 0-100
  status: 'Active' | 'In Custody' | 'Released' | 'Wanted';
  quickStats: {
    totalFIRs: number;
    firstOffenseDate: Date;
    lastOffenseDate: Date;
    activeCases: number;
  };
}

/**
 * Criminal history entry
 */
export interface CriminalHistoryEntry {
  firId: string;
  firNumber: string;
  date: Date;
  crimeType: string;
  status: string;
  description: string;
  severity: 'Minor' | 'Moderate' | 'Severe' | 'Critical';
  location: string;
  district: string;
}

/**
 * Behavioral profile (Rational Choice Theory analysis)
 */
export interface BehavioralProfile {
  personId: string;
  preferredTime: {
    hourRange: string; // "22:00-02:00"
    dayOfWeek: string; // "Friday, Saturday"
    visualization: 'clock'; // UI hint
  };
  targetProfile: {
    description: string; // "Elderly women, isolated locations"
    commonTraits: string[];
    icon: string;
  };
  modusOperandi: {
    method: string; // "Chain snatching from behind on two-wheeler"
    consistencyScore: number; // 0-100
    patterns: string[];
  };
  geographicRange: {
    centerLat: number;
    centerLng: number;
    radiusKm: number;
    districts: string[];
  };
  escalationTrend: {
    trend: 'escalating' | 'stable' | 'de-escalating';
    description: string;
    dataPoints: Array<{ date: Date; severity: number }>;
  };
  moConsistency: number; // 0-100, how consistent the MO is
  confidence: number; // 0-100
}

/**
 * Network connection
 */
export interface NetworkConnection {
  personId: string;
  name: string;
  relationshipType: 'Co-accused' | 'Associate' | 'Family' | 'Contact';
  strength: number; // 0-100
  sharedFIRs: number;
  firstSeen: Date;
  lastSeen: Date;
}

/**
 * Linked entity (vehicle, phone, bank account, address)
 */
export interface LinkedEntity {
  type: 'Vehicle' | 'Phone' | 'BankAccount' | 'Address';
  value: string;
  firCount: number;
  firstSeen: Date;
  lastSeen: Date;
  status?: string;
}

/**
 * Investigation note
 */
export interface InvestigationNote {
  id: string;
  personId: string;
  author: string; // Officer name
  content: string;
  createdAt: Date;
  updatedAt: Date;
  tags: string[];
}

/**
 * Investigation lead (auto-generated)
 */
export interface InvestigationLead {
  id: string;
  description: string;
  priority: 'High' | 'Medium' | 'Low';
  source: 'Graph' | 'Pattern' | 'Theory' | 'Similarity';
  confidence: number; // 0-100
  actionable: boolean;
  details?: string;
}

/**
 * Case with linked FIRs
 */
export interface Case {
  caseId: string;
  caseNumber: string;
  linkedFIRs: string[]; // FIR IDs
  status: 'Under Investigation' | 'Chargesheeted' | 'Trial' | 'Convicted' | 'Acquitted';
  investigatingOfficer: string;
  district: string;
  dateOpened: Date;
  dateUpdated: Date;
}

/**
 * Case summary (auto-generated by LLM)
 */
export interface CaseSummary {
  caseId: string;
  summary: string; // LLM-generated narrative
  keyFacts: {
    crimeType: string;
    location: string;
    date: Date;
    accusedNames: string[];
    victimNames: string[];
    evidenceCount: number;
  };
  generatedAt: Date;
  regenerable: boolean;
}

/**
 * Case timeline event
 */
export interface CaseTimelineEvent {
  eventType: 'FIR Filed' | 'Investigation Started' | 'Evidence Collected' | 'Accused Identified' | 'Chargesheet Filed' | 'Trial Started' | 'Verdict';
  date: Date;
  description: string;
  actor?: string; // Officer or court
  status?: string;
}

/**
 * Similar case
 */
export interface SimilarCase {
  caseId: string;
  caseNumber: string;
  summary: string;
  outcome: string;
  similarityScore: number; // 0-100
  moComparison: string;
  crimesTypes: string[];
  dateRange: { start: Date; end: Date };
}

/**
 * FIR detail
 */
export interface FIRDetail {
  firId: string;
  firNumber: string;
  date: Date;
  station: string;
  district: string;
  investigatingOfficer: string;
  crimeType: string;
  ipcSections: string[];
  description: string; // Full narrative
  location: {
    address: string;
    latitude?: number;
    longitude?: number;
  };
  status: string;
  statusHistory: Array<{ status: string; date: Date; updatedBy: string }>;
  linkedPersons: {
    accused: Array<{ id: string; name: string; age: number }>;
    victims: Array<{ id: string; name: string; age: number }>;
    witnesses: Array<{ id: string; name: string; age: number }>;
  };
  linkedEntities: {
    vehicles: string[];
    weapons: string[];
    phoneRecords: string[];
  };
  evidenceFiles: Array<{ filename: string; type: string; uploadedAt: Date }>;
}

/**
 * Offender search filters
 */
export interface OffenderSearchFilters {
  role?: ('Accused' | 'Victim' | 'Witness')[];
  riskScoreRange?: { min: number; max: number };
  districts?: string[];
  crimeTypes?: string[];
  status?: string[];
  minFIRCount?: number;
}

/**
 * Case search filters
 */
export interface CaseSearchFilters {
  status?: string[];
  districts?: string[];
  dateRange?: { start: Date; end: Date };
  investigatingOfficer?: string;
  crimeTypes?: string[];
}

/**
 * Offender list item (for table)
 */
export interface OffenderListItem {
  personId: string;
  name: string;
  age: number;
  gender: string;
  riskScore: number;
  firCount: number;
  lastKnownStatus: string;
  district: string;
  role: string;
}

/**
 * Case list item (for table)
 */
export interface CaseListItem {
  caseId: string;
  caseNumber: string;
  linkedFIRCount: number;
  status: string;
  investigatingOfficer: string;
  district: string;
  dateOpened: Date;
}

/**
 * Profile query parameters
 */
export interface ProfileQuery {
  personId: string;
  includeHistory?: boolean;
  includeBehavioralProfile?: boolean;
  includeNetwork?: boolean;
  includeLinkedEntities?: boolean;
  includeLeads?: boolean;
}

/**
 * Case query parameters
 */
export interface CaseQuery {
  caseId: string;
  includeSummary?: boolean;
  includeTimeline?: boolean;
  includeSimilarCases?: boolean;
  includeLeads?: boolean;
}
