import React from 'react';

interface PrintFooterProps {
  auditId?: string;
}

export function PrintFooter({ auditId = 'SYS-AUTO' }: PrintFooterProps) {
  return (
    <div className="hidden print:block fixed bottom-0 left-0 right-0 border-t border-slate-300 pt-2 text-center text-[10px] text-slate-500 bg-white">
      <p suppressHydrationWarning>Generated by CrimeIntel AI — Audit ID: {auditId}-{Math.floor(Math.random() * 10000)}</p>
      <p>This report contains sensitive law enforcement data. Do not distribute without authorization.</p>
    </div>
  );
}
